### ISSUE TITLE
Etch 0.6.2 doesn't seem to work with Backbone 1.1.0

### ISSUE THREAD

**Issue by yookoala** [joshontheweb/etch#28]
Hello. I've just tried to setup the example with some changes to libraries' versions. When I used Etch 0.6.2 against Backbone 1.1.0, an error occurs:
`TypeError: this.$el.off is not a function`

The same issue exists with Backbone 1.0.0. But when I downgraded the Backbone version to 0.9.0, things work fine. I tested on Firefox and Chrome. Both have the same result.

Here are the HTML I used for this test:

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"> 
<title>Etch Test</title>
<link type="text/css" rel="stylesheet" href="./css/etch.css" />
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.0/backbone-min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/rangy/1.2.3/rangy-core.js"></script>
<script type="text/javascript" src="./js/etch.js"></script>
</head>
<body>
  <section id="main">
    <div class="article">
        <h3 class="title editable" data-button-class="title">
            This is an editable title
        </h3>
        <div class="body editable" data-button-class="all">
            Text with a light blue background is editable.  You will find it easy to use etch to <u>underline</u> text as well as <b>bold</b> and <i>italic</i>.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.               
        </div>
    </div>
  </section>
</body>
<script type="text/javascript">

(function() {
    var article = Backbone.Model.extend({
        defaults: {
            title: 'Default Title',
            body: 'Default body text'
        }
    });

    var articleView = Backbone.View.extend({
        initialize: function() {
            _.bindAll(this, 'save')
            this.model.bind('save', this.save);
        },

        events: {
            'mousedown .editable': 'editableClick'
        },

        editableClick: etch.editableInit,

        save: function() {

            // normally you would call model.save() here but this is a demo
            $(this.el).find('.editable').effect('highlight', {color: 'yellow'});
            $('.save-event').fadeIn('fast', function() {
                setTimeout($(this).fadeOut('slow'), 10000);
            });
        }

    });

    $article = $('.article');
    var model = new article();
    var view = new articleView({model: model, el: $article[0], tagName: $article[0].tagName});
})()

</script>
</html>


```
